export const ACTION_TYPE = {
  OPEN_CELL: 'OPEN_CELL',
  MARK_CELL: 'MARK_CELL',
  START_NEW_GAME: 'START_NEW_GAME',
  CHANGE_VALUE: 'CHANGE_VALUE',
  CHANGE_COUNT_BOMBS: 'CHANGE_COUNT_BOMBS',
  APPLY_CHANGES: 'APPLY_CHANGES',
};
